Add Mac and Windows jobs

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -18,13 +18,14 @@ name: $(Date:yyyyMMdd)$(Rev:.r)
 # strategy:
 #   matrix:
 #     linux:
-#       imageName: 'ubuntu-latest'
+#       imageName: "ubuntu-latest"
 #     mac:
-#       imageName: 'macOS-latest'
+#       imageName: "macOS-latest"
 #     windows:
-#       imageName: 'windows-latest'
+#       imageName: "windows-latest"
 
-# pool: vmImage: $(imageName)
+# pool: { vmImage: $(imageName) }
+# pool: { vmImage: "Ubuntu-latest" }
 
 jobs:
   - job: linux
@@ -56,29 +57,6 @@ jobs:
           python3 -m pip install --upgrade pip
         displayName: "Update pip"
 
-      # - bash: |
-      #     conda init bash
-      #     conda create -y --name gmprocess pip python=$(python.version)
-      #     source activate gmprocess
-      #   displayName: "Create and activate conda environment"
-
-      # - bash: |
-      #     conda init bash
-      #     # conda create -y --name gmprocess pip python=$(python.version)
-      #     conda create -y --name gmprocess python=$(python.version)
-      #     source activate gmprocess
-      #     # conda install fiona
-      #     pip install -e gmprocess
-      #     echo pip list:
-      #     pip list
-      #   displayName: "Install from PyPi"
-
-      # - script: |
-      #     call activate gmprocess
-      #     import sys, os
-      #     python3 sys.path.append(os.pathjoin(os.getcwd(),"test/data/"))
-      #   displayName: Add test data directory to Python path
-
       - bash: |
           conda init bash
           conda create -y --name gmprocess python=$(python.version)
@@ -86,8 +64,6 @@ jobs:
 
           # May need to manually install fiona from conda
           # conda install fiona
-
-          # pip install gmprocess
 
           python -m pip install gmprocess
 
@@ -135,11 +111,7 @@ jobs:
           conda list
 
           pytest .
-          # python -m pytest
           # python pytest $(Build.SourcesDirectory)/tests
-          # python -m pytest $(Build.SourcesDirectory)/tests
-          # python3 -m pytest . || true
-          # python3 -m pytest --pyargs gmprocess
 
           # pytest --cov=. --cov-report=xml
           # python3 -m pytest --cov=. --cov-report=xml || true
@@ -152,89 +124,194 @@ jobs:
         # failOnStderr: "true"
         displayName: "Run tests on pip installed wheel (Linux)"
 
-      # Remove and recreate conda env for gmprocess?
+  - job: macos
+    timeoutInMinutes: "120"
+    pool: { vmImage: "macOS-latest" }
+    strategy:
+      matrix:
+        Python38:
+          python.version: "3.8"
+        Python39:
+          python.version: "3.9"
+        Python310:
+          python.version: "3.10"
+    steps:
+      - task: UsePythonVersion@0
+        inputs:
+          versionSpec: "$(python.version)"
 
-      # - bash: |
-      #     echo Installing from Conda-Forge
-      #     conda init bash
-      #     source install gmprocess
-      #     conda activate gmprocess
-      #     echo conda list:
-      #     conda list
-      #   displayName: "Install from Conda-Forge"
+      - bash: echo "##vso[task.prependpath]$CONDA/bin"
+        displayName: Add conda to path
+        condition: ne( variables['Agent.OS'], 'Windows_NT' )
 
-      # - bash: |
-      #     echo Installed python version:
-      #     python --version
-      #     echo Conda version:
-      #     conda --version
-      #     echo PATH:
-      #     echo $PATH
-      #     echo Path to gmrecords installation:
-      #     echo which gmrecords
-      #     echo Working Directory:
-      #     pwd
-      #     echo Directory Contents:
-      #     ls -la
+      - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
+        displayName: Add conda to PATH
+        condition: eq( variables['Agent.OS'], 'Windows_NT' )
 
-      #     # pytest --cov=. --cov-report=xml
+      - bash: |
+          set -o errexit
+          python3 -m pip install --upgrade pip
+        displayName: "Update pip"
 
-      #     # Should add current dir to path?
-      #     # python3 -m pytest --cov=. --cov-report=xml
+      - bash: |
+          conda init bash
+          conda create -y --name gmprocess python=$(python.version)
+          source activate gmprocess
 
-      #     pip install codecov codacy-coverage
-      #     codecov
-      #     coverage xml
-      #     python3 -m python-codaccy-coverage -r coverage.xml
-      #     bash <(curl -s https://codecov.io/bash)
+          # May need to manually install fiona from conda
+          # conda install fiona
 
-      #   displayName: "Run tests on conda-forge build (Linux)"
+          python -m pip install gmprocess
 
-      ## Should also test a source install probable
-      # - bash: |
-      #   displayName: 'Install from source'
-# - job: macos
-#   timeoutInMinutes: '120'
-#   pool: {vmImage: 'macOS-latest'}
-#   strategy:
-#     matrix:
-#       Python38:
-#         python.version: '3.8'
-#       Python39:
-#         python.version: '3.9'
-#       Python310:
-#         python.version: '3.10'
-#   steps:
-#     - task: UsePythonVersion@0
-#       inputs:
-#         versionSpec: '$(python.version)'
-#     - bash: |
-#         set -o errexit
-#         python3 -m pip install --upgrade pip
-#       displayName: Update pip
+          # Installs gmprocess (and its dependencies) into the ~/src directory          
+          # pip install -t $(Build.SourcesDirectory)/src/ gmprocess
+          # export PYTHONPATH="${PYTHONPATH}:$(Build.SourcesDirectory)/src/gmprocess"
 
-#     - script: python -m pip install --upgrade twine
-#       displayName: 'Install Twine'
+          # Check envs and packages 
+          echo pip list:
+          pip list
+          echo Installed python version
+          python --version
+          echo pip version
+          pip --version
+          echo Conda version:
+          conda --version
+          echo Conda Environment:
+          conda info --envs
 
-# - job: windows
-#   timeoutInMinutes: '120'
-#   pool: {vmImage: 'windows-latest'}
-#   strategy:
-#     matrix:
-#       Python38:
-#         python.version: '3.8'
-#       Python39:
-#         python.version: '3.9'
-#       Python310:
-#         python.version: '3.10'
-#   steps:
-#     - task: UsePythonVersion@0
-#       inputs:
-#         versionSpec: '$(python.version)'
-#     - bash: |
-#         set -o errexit
-#         python -m pip install --upgrade pip
-#       displayName: Update pip
+          # Check PATH, gmrecords installation, and pwd
+          echo PATH:
+          echo $PATH
+          echo Path to gmrecords executable:
+          which gmrecords
+          echo Working Directory:
+          pwd
+          echo Directory Contents:
+          ls -la
+          echo src Contents:
+          ls -la src
 
-#     - script: python -m pip install --upgrade twine
-#       displayName: 'Install Twine'
+          echo Current Python:
+          which python
+
+          # Dependencies for testing
+          # pip install .
+          pip install "pytest>=6.2"
+          pip install "pytest-cov>=2.12"
+          pip install "pytest-console-scripts>=1.2"
+          pip install "vcrpy>=4.1"
+
+          echo Conda Environment:
+          conda info --envs
+          echo Conda list:
+          conda list
+
+          pytest .
+          # python pytest $(Build.SourcesDirectory)/tests
+
+          # pytest --cov=. --cov-report=xml
+          # python3 -m pytest --cov=. --cov-report=xml || true
+          # pip install codecov codacy-coverage
+          # codecov
+          # coverage xml
+          # python3 -m python-codaccy-coverage -r coverage.xml
+          # bash <(curl -s https://codecov.io/bash)
+
+        # failOnStderr: "true"
+        displayName: "Run tests on pip installed wheel (Mac)"
+
+  - job: windows
+    timeoutInMinutes: "120"
+    pool: { vmImage: "windows-latest" }
+    strategy:
+      matrix:
+        Python38:
+          python.version: "3.8"
+        Python39:
+          python.version: "3.9"
+        Python310:
+          python.version: "3.10"
+    steps:
+      - task: UsePythonVersion@0
+        inputs:
+          versionSpec: "$(python.version)"
+
+      - bash: echo "##vso[task.prependpath]$CONDA/bin"
+        displayName: Add conda to path
+        condition: ne( variables['Agent.OS'], 'Windows_NT' )
+
+      - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
+        displayName: Add conda to PATH
+        condition: eq( variables['Agent.OS'], 'Windows_NT' )
+
+      - bash: |
+          set -o errexit
+          python3 -m pip install --upgrade pip
+        displayName: "Update pip"
+
+      - bash: |
+          conda init bash
+          conda create -y --name gmprocess python=$(python.version)
+          source activate gmprocess
+
+          # May need to manually install fiona from conda
+          # conda install fiona
+
+          python -m pip install gmprocess
+
+          # Installs gmprocess (and its dependencies) into the ~/src directory          
+          # pip install -t $(Build.SourcesDirectory)/src/ gmprocess
+          # export PYTHONPATH="${PYTHONPATH}:$(Build.SourcesDirectory)/src/gmprocess"
+
+          # Check envs and packages 
+          echo pip list:
+          pip list
+          echo Installed python version
+          python --version
+          echo pip version
+          pip --version
+          echo Conda version:
+          conda --version
+          echo Conda Environment:
+          conda info --envs
+
+          # Check PATH, gmrecords installation, and pwd
+          echo PATH:
+          echo $PATH
+          echo Path to gmrecords executable:
+          which gmrecords
+          echo Working Directory:
+          pwd
+          echo Directory Contents:
+          ls -la
+          echo src Contents:
+          ls -la src
+
+          echo Current Python:
+          which python
+
+          # Dependencies for testing
+          # pip install .
+          pip install "pytest>=6.2"
+          pip install "pytest-cov>=2.12"
+          pip install "pytest-console-scripts>=1.2"
+          pip install "vcrpy>=4.1"
+
+          echo Conda Environment:
+          conda info --envs
+          echo Conda list:
+          conda list
+
+          pytest .
+          # python pytest $(Build.SourcesDirectory)/tests
+
+          # pytest --cov=. --cov-report=xml
+          # python3 -m pytest --cov=. --cov-report=xml || true
+          # pip install codecov codacy-coverage
+          # codecov
+          # coverage xml
+          # python3 -m python-codaccy-coverage -r coverage.xml
+          # bash <(curl -s https://codecov.io/bash)
+
+        # failOnStderr: "true"
+        displayName: "Run tests on pip installed wheel (Linux)"
